import { useQuery } from '@tanstack/react-query';
import { api } from '../lib/api';

export default function AiBrief() {
  const { data, isLoading, error } = useQuery({
    queryKey: ['ai-brief'],
    queryFn: api.aiBrief,
    staleTime: 30 * 60 * 1000, // 30 min — brief doesn't change within a trading day
    retry: false,
  });

  if (isLoading) {
    return (
      <Frame>
        <div className="text-sm text-slate-500 dark:text-slate-400">
          Generating today's brief… (first hit takes a few seconds while Claude writes it)
        </div>
      </Frame>
    );
  }

  if (error) {
    const msg = error instanceof Error ? error.message : String(error);
    return (
      <Frame>
        <div className="text-xs text-amber-600 dark:text-amber-400">
          AI Brief unavailable: {msg}. Add <code className="font-mono">ANTHROPIC_API_KEY</code> to{' '}
          <code className="font-mono">backend/.env</code> if you haven't.
        </div>
      </Frame>
    );
  }

  if (!data) return null;

  const generated = new Date(data.generated_at * 1000);
  const generatedLabel = generated.toLocaleString(undefined, {
    timeZone: 'America/New_York',
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });

  return (
    <Frame>
      <div className="flex items-center gap-2 text-[10px] uppercase tracking-widest text-emerald-700 dark:text-emerald-400 mb-2">
        <span>Today's AI Brief</span>
        <span className="text-slate-400 dark:text-slate-500">· {data.date}</span>
      </div>

      <h1 className="text-xl sm:text-2xl font-serif font-semibold text-slate-900 dark:text-slate-100 leading-tight mb-5">
        {data.headline}
      </h1>

      <ol className="space-y-4 mb-6">
        {data.bullets.map((b, i) => (
          <li key={i} className="flex gap-3">
            <span className="font-mono text-xs text-slate-400 dark:text-slate-500 mt-0.5 shrink-0 w-5">
              {String(i + 1).padStart(2, '0')}
            </span>
            <div className="flex-1 min-w-0">
              <div className="text-sm font-semibold text-slate-900 dark:text-slate-100">
                {b.title}
              </div>
              <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed mt-0.5">
                {b.body}
              </p>
              {b.tickers.length > 0 && (
                <div className="mt-1.5 flex flex-wrap gap-1">
                  {b.tickers.map((t) => (
                    <span
                      key={t}
                      className="font-mono text-[10px] px-1.5 py-0.5 rounded bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300"
                    >
                      {t}
                    </span>
                  ))}
                </div>
              )}
            </div>
          </li>
        ))}
      </ol>

      <div className="border-t border-slate-200 dark:border-slate-800 pt-3">
        <div className="text-[10px] uppercase tracking-widest text-slate-500 dark:text-slate-400 mb-2">
          What to watch today
        </div>
        <ul className="space-y-1">
          {data.watch_today.map((w, i) => (
            <li key={i} className="text-sm text-slate-700 dark:text-slate-300 flex items-baseline gap-2">
              <span className="text-slate-400 dark:text-slate-500">·</span>
              <span className="flex-1">{w.label}</span>
              {w.when && (
                <span className="font-mono text-xs text-slate-500 dark:text-slate-400 whitespace-nowrap">
                  {w.when}
                </span>
              )}
            </li>
          ))}
        </ul>
      </div>

      <div className="text-[10px] text-slate-400 dark:text-slate-500 mt-4">
        Generated by {data.model} · {generatedLabel} ET
      </div>
    </Frame>
  );
}

function Frame({ children }: { children: React.ReactNode }) {
  return (
    <article className="rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/40 p-6 mb-8">
      {children}
    </article>
  );
}
